# Generated by Django 2.2.4 on 2019-08-09 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Cli_Nombre', models.CharField(max_length=25, verbose_name='Nombres')),
                ('Cli_Apellido', models.CharField(max_length=25)),
                ('Cli_TipoID', models.CharField(choices=[('TI', 'TI'), ('CC', 'CC')], default='TI', max_length=2)),
                ('Cli_Identificacion', models.IntegerField()),
                ('Cli_Direccion', models.CharField(max_length=50)),
                ('Cli_Telefono', models.CharField(max_length=50)),
                ('Cli_Persona', models.CharField(choices=[('Natural', 'N'), ('Juridica', 'J')], default='Natural', max_length=10)),
                ('Cli_Estado', models.CharField(choices=[('0', 'Activo'), ('1', 'Desactivo')], default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoid', models.CharField(choices=[('TI', 'TI'), ('CC', 'CC')], default='1', max_length=1)),
                ('identificacion', models.IntegerField()),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='profile_image/zx.jpg', upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('com_tipo', models.CharField(choices=[('0', 'Dolares a Pesos'), ('1', 'Pesos a Dolares')], default='0', max_length=2)),
                ('Com_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Com_Precio', models.CharField(max_length=50)),
                ('Com_Cantidad', models.CharField(max_length=50)),
                ('Com_Cliente_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changehouse.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='Cli_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changehouse.UserProfile'),
        ),
    ]
