# Generated by Django 2.0 on 2018-11-18 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Cli_Nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('Cli_Apellido', models.CharField(max_length=25)),
                ('Cli_TipoID', models.CharField(choices=[('0', 'TI'), ('1', 'CC'), ('2', 'PA')], default='0', max_length=1)),
                ('Cli_Identificacion', models.IntegerField()),
                ('Cli_Direccion', models.CharField(max_length=50)),
                ('Cli_Telefono', models.CharField(max_length=50)),
                ('Cli_Persona', models.CharField(choices=[('0', 'Natural'), ('1', 'Juridica')], default='0', help_text='Tipo de persona', max_length=1)),
                ('Cli_Estado', models.CharField(choices=[('0', 'Activo'), ('1', 'Desactivo')], default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoid', models.CharField(choices=[('0', 'TI'), ('1', 'CC'), ('2', 'PA')], default='1', max_length=1)),
                ('identificacion', models.IntegerField()),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='profile_image/zx.jpg', upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VentaCompra',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('Ven_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Ven_Precio', models.CharField(max_length=50)),
                ('Ven_Cantidad', models.CharField(max_length=50)),
                ('Ven_Total', models.CharField(max_length=50)),
                ('Ven_Cliente_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changehouse.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='Cli_User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changehouse.UserProfile'),
        ),
    ]
