# Generated by Django 2.0 on 2018-11-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Cli_Nombre',
            field=models.CharField(max_length=25, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Cli_Persona',
            field=models.CharField(choices=[('Natural', 'si'), ('Juridica', 'NO')], default='Natural', max_length=10),
        ),
    ]
