# Generated by Django 2.2.28 on 2022-11-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='Com_Precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Ven_Precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
