# Generated by Django 2.0 on 2018-11-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changehouse', '0002_auto_20181119_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Cli_Estado',
            field=models.CharField(choices=[('0', 'Activo'), ('1', 'Desactivo')], default='TI', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Cli_Persona',
            field=models.CharField(choices=[('Natural', 'N'), ('Juridica', 'J')], default='Natural', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Cli_TipoID',
            field=models.CharField(choices=[('TI', 'TI'), ('CC', 'CC')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tipoid',
            field=models.CharField(choices=[('TI', 'TI'), ('CC', 'CC')], default='1', max_length=1),
        ),
    ]
