# Generated by Django 2.2.28 on 2022-11-30 02:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('changehouse', '0002_auto_20221129_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('terminada', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'Tarea',
            },
        ),
        migrations.RemoveField(
            model_name='compra',
            name='Com_Cambista_ID',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='Com_Cliente_ID',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='Ven_Cambista_ID',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='Ven_Cliente_ID',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
