# Generated by Django 2.2.4 on 2019-08-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changehouse', '0002_auto_20190815_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='Com_Cambista_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='changehouse.UserProfile'),
            preserve_default=False,
        ),
    ]
