# Generated by Django 2.0 on 2018-11-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changehouse', '0003_auto_20181120_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Cli_Estado',
            field=models.CharField(choices=[('0', 'Activo'), ('1', 'Desactivo')], default='TI', max_length=3),
        ),
    ]
