# Generated by Django 2.2.4 on 2019-08-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changehouse', '0003_compra_com_cambista_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='Com_Precio',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
    ]
