# Generated by Django 2.2.4 on 2019-08-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changehouse', '0004_auto_20190824_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='Com_tipo',
            field=models.CharField(choices=[('Dolares a Pesos', 'Dolares a Pesos'), ('Pesos a Dolares', 'Pesos a Dolares')], default='Pesos a Dolares', max_length=20),
        ),
    ]
