# Generated by Django 2.2.28 on 2022-11-30 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changehouse', '0004_auto_20221129_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Cli_User_ID',
        ),
    ]
