# Generated by Django 2.2.4 on 2019-08-25 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('changehouse', '0005_auto_20190824_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('Ven_Tipo', models.CharField(choices=[('Dolares a Pesos', 'Dolares a Pesos'), ('Pesos a Dolares', 'Pesos a Dolares')], default='Pesos a Dolares', max_length=20)),
                ('Ven_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Ven_Precio', models.DecimalField(decimal_places=2, max_digits=65)),
                ('Ven_Cantidad', models.CharField(max_length=50)),
                ('Ven_Total', models.CharField(max_length=50)),
                ('Ven_Pago', models.CharField(max_length=50)),
                ('Ven_Vuelto', models.CharField(max_length=50)),
                ('Ven_Cambista_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changehouse.UserProfile')),
                ('Ven_Cliente_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='changehouse.Cliente')),
            ],
        ),
    ]
